#!/bin/bash
VOL=`pactl list sinks | grep '^[[:space:]]Volume:' |     head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`
NEW_VOL=$(($VOL + 10))
pactl -- set-sink-volume 0 ${NEW_VOL}%
