#!/bin/bash
# Copied from this URL:
# https://unix.stackexchange.com/questions/132230/read-out-pulseaudio-volume-from-commandline-i-want-pactl-get-sink-volume
CUR_VOL=`pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`
new_vol=`python3 -c "print(min(100, ${CUR_VOL} + 10))"`
pactl set-sink-volume 0 ${new_vol}%
